-- QUESTION TABLE
-- ===============================
-- Part A (E/I)
INSERT INTO Questions (question) VALUES ("I like being around people");
INSERT INTO Questions (question) VALUES ("I am more interested in people than in their ideas");
INSERT INTO Questions (question) VALUES ("I have many friends");
INSERT INTO Questions (question) VALUES ("I am popular in school");
INSERT INTO Questions (question) VALUES ("When I am feeling down, I seek out company to cheer myself up.");

-- Part B (S/N)
INSERT INTO Questions (question) VALUES ("I am a logical person");
INSERT INTO Questions (question) VALUES ("I am very practical");
INSERT INTO Questions (question) VALUES ("I am a realist");
INSERT INTO Questions (question) VALUES ("I like dealing with facts");
INSERT INTO Questions (question) VALUES ("I don’t trust hunches or anything that cannot be proven");

-- Part C (F/T)
INSERT INTO Questions (question) VALUES ("I like to base my decisions on what is reasonable");
INSERT INTO Questions (question) VALUES ("I think that justice is more important than mercy");
INSERT INTO Questions (question) VALUES ("I like to speak the truth even if the truth hurts");
INSERT INTO Questions (question) VALUES ("I don’t like people who change their minds often");
INSERT INTO Questions (question) VALUES ("I like to be disciplined and in control");

-- Part D (J/P)
INSERT INTO Questions (question) VALUES ("I am very organized");
INSERT INTO Questions (question) VALUES ("I like to keep to a schedule");
INSERT INTO Questions (question) VALUES ("I like to plan ahead");
INSERT INTO Questions (question) VALUES ("I get upset if activities or plans change at the last minute");
INSERT INTO Questions (question) VALUES ("I am always punctual");


-- PERSONALITY TABLE
-- ===============================
INSERT INTO Personalities (personType, personTitle, personWords, personDescription, personImageURL, personStrengths, personWeaknesses, personOverview, mentalAgeTitle, mentalAgeDescription, animalTitle, animalDescription, officeTitle, officeDescription, pizzaTitle, pizzaDescription, coffeeTitle, coffeeDescription, travelTitle, travelDescription) 
VALUES 
(`INFP`, `INFP: The Healer`, `(Introverted, Intuitive, Feeling, Perceiving)`, `INFP is an acronym used to describe one of the sixteen personality types created by Katharine Briggs and Isabel Myers. It stands for Introverted, iNtuitive, Feeling, Perceiving. INFP indicates a person who is energized by time alone (Introverted), who focuses on ideas and concepts rather than facts and details (iNtuitive), who makes decisions based on feelings and values (Feeling) and who prefers to be spontaneous and flexible rather than planned and organized (Perceiving). INFPs are sometimes referred to as Healer personalities due to their sympathetic idealism and gentle compassion for other people.`, `INFP.png`, `Idealism
Integrity
Compromise
Dedication`, `Sensitivity
Impracticality
Selflessness
Vulunerability`, `INFPs are imaginative idealists, guided by their own core values and beliefs. To a Healer, possibilities are paramount; the realism of the moment is only of passing concern. They see potential for a better future, and pursue truth and meaning with their own individual flair.

INFPs are sensitive, caring, and compassionate, and are deeply concerned with the personal growth of themselves and others. Individualistic and nonjudgmental, INFPs believe that each person must find their own path. They enjoy spending time exploring their own ideas and values, and are gently encouraging to others to do the same. INFPs are creative and often artistic; they enjoy finding new outlets for self-expression.`, `INFP – 60`, `No matter what your biological age is, you were born as and remain an old soul. You have been questioning the greater truths about life for as long as you can remember, but your wisdom is supported by an inherently youthful sense of curiosity that drives you to explore each issue from multiple different angles. You may best be best described as 60 going on 6 – you have the sagacity of someone much older than yourself but the insatiable curiosity of someone much younger.`, `INFP – The Asian Elephant`, `Compassionate, wise, and even sentimental, we couldn’t imagine a better fit for the INFP personality type. These gentle giants are one of the only animals that show a great capacity for empathy. Researchers have watched female elephants help baby elephants climb up muddy banks or out of holes. They’ve seen elephants assisting others that are injured, pulling out tranquilizer darts, or even spraying dust on each other’s wounds. These empathic animals even mourn their dead and comfort other elephants that are mourning. On top of this, elephants are creative – they work together to solve puzzles and can even paint portraits!`, `INFP: Pam Beesly`, `As an INFP personality, Pam may seem reserved on the outside, but on the inside she's bubbling with passion for the things she loves, like art. In the beginning of the series, Pam's mode of handling conflict was totally INFP behavior — avoiding confrontation at all costs and trying to remain diplomatic at all times — but then, we got to see her come out of her shell more and stand up for herself, and it was a beautiful thing. Like other INFPs, Pam also looks at love and relationships in an idealistic way, and she definitely got exactly the fairytale that she wanted in Jim.`);, 

INSERT INTO Personalities (personType, personTitle, personWords, personDescription, personImageURL, personStrengths, personWeaknesses, personOverview, mentalAgeTitle, mentalAgeDescription, animalTitle, animalDescription, officeTitle, officeDescription, pizzaTitle, pizzaDescription, coffeeTitle, coffeeDescription, travelTitle, travelDescription) 
VALUES 
(`INFJ`, `INFJ: The Counselor`, `(Introverted, Intuitive, Feeling, Judging)`, `INFJ is one of the sixteen personality types created by Katharine Briggs and Isabel Myers. INFJ is an acronym for the personality traits of Introversion, iNtuition, Feeling, and Judging. The INFJ type is also called the 'Counselor' and is described as idealistic, compassionate, and sensitive.

Each of the four letters of the INFJ code signifies a key personality trait of this type. INFJs are energized by time alone (Introverted), focus on ideas and concepts rather than facts and details (iNtuitive), make decisions based on feelings and values (Feeling) and prefer to be planned and organized rather than spontaneous and flexible (Judging).`, `INFJ.png`, `Practical insight
Compassion
Keeping the peace
Decisiveness`, `Overlooking details
Intensely private
Conflict averse
Sensitive`, `INFJs are creative nurturers with a strong sense of personal integrity and a drive to help others realize their potential. Creative and dedicated, they have a talent for helping others with original solutions to their personal challenges.

The Counselor has a unique ability to intuit others' emotions and motivations, and will often know how someone else is feeling before that person knows it himself. They trust their insights about others and have strong faith in their ability to read people. Although they are sensitive, they are also reserved; the INFJ is a private sort, and is selective about sharing intimate thoughts and feelings.`, `INFJ – 90`, `Chances are, some part of you has always felt older than those around you. You dwell eternally in the deep end of life – questioning its nature and meaning in depth, while remaining endlessly patient with those around you. You have the empathy and insight of someone much older than yourself – you are a natural sage, regardless of your biological age.`, `INFJ – The Humpback Whale`, `Empathetic, protective, and even introverted – these gentle giants are the closest animal we could find to embodying the INFJ personality type. Unusually protective of even those outside their species, they will deliberately interfere with attacking killer whales to help others in distress – helping animals like gray whale calves, seals, and other sea creatures. Peace-loving and known for their complex songs, these animals capture the compassionate, insightful nature of the INFJ.`, `INFJ: Angela Martin`, `INFJs are rare, but then again, isn't Angela? They hold integrity as a core personal value, which relates to how Angela loves to play by the rules and do everything by the book. They're hard to get close to and they can get pretty intense when it comes to their beliefs being put into question, but much like Angela, an INFJ can make a deep connection with anyone they choose to get close to (like Dwight).`);

INSERT INTO Personalities (personType, personTitle, personWords, personDescription, personImageURL, personStrengths, personWeaknesses, personOverview, mentalAgeTitle, mentalAgeDescription, animalTitle, animalDescription, officeTitle, officeDescription, pizzaTitle, pizzaDescription, coffeeTitle, coffeeDescription, travelTitle, travelDescription) 
VALUES 
(`ENFJ`, `ENFJ: The Teacher`, `(Extroverted, Intuitive, Feeling, Judging)`, `ENFJ is an acronym used to describe one of the sixteen personality types created by Katharine Briggs and Isabel Myers. It stands for Extraverted, iNtuitive, Feeling, Judging. ENFJ indicates a person who is energized by time spent with others (Extraverted), who focuses on ideas and concepts rather than facts and details (iNtuitive), who makes decisions based on feelings and values (Feeling) and who prefers to be planned and organized rather than spontaneous and flexible (Judging). ENFJs are sometimes referred to as Teacher personalities because of their interest in helping others develop and grow.`, `ENFJ.png`, `Peacekeeping
Communication
Persuasiveness
Leadership`, `Leap before looking
Overcommitment
Struggle to make tough decisions
Too selfless`, `ENFJs are idealist organizers, driven to implement their vision of what is best for humanity. They often act as catalysts for human growth because of their ability to see potential in other people and their charisma in persuading others to their ideas. They are focused on values and vision, and are passionate about the possibilities for people.

ENFJs are typically energetic and driven, and often have a lot on their plates. They are tuned into the needs of others and acutely aware of human suffering; however, they also tend to be optimistic and forward-thinking, intuitively seeing opportunity for improvement. The ENFJ is ambitious, but their ambition is not self-serving: rather, they feel personally responsible for making the world a better place.`, `ENFJ – 40`, `You’ve always naturally assumed the role of the wise mentor to those in your life. Your mental prowess resembles that of someone who is old enough to make decisions rationally and compassionately, yet young enough to execute them with an idealistic sense of enthusiasm. Your “Mother Hen” role in others’ lives plants you at the beginning of middle-age, mentally. You have a youthful energy backed up by an indisputable well of wisdom.`, `ENFJ – The Arabian Horse`, `Gentle, intelligent, and persistent – Arabian horses capture many of the strengths of the ENFJ personality type. These dazzling horses are known for their responsiveness to humans. In fact, they’re one of the best horses for families and children and can often recognize and respond to human emotions. They are also known for their passionate spirit – their endurance is considered higher than any other racing horse. When they have a goal there’s nearly nothing that can stop them – much like the ENFJ.`, `ENFJ: Kelly Kapoor`, `Like a typical ENFJ, Kelly is filled with passion and is a very social person. She's usually in a good mood and ready to have a great time, even at work. It's said that people who have ENFJ personalities jump immediately into a big commitment in their romantic relationships, and... well, we've seen exactly that happen with Ryan, even though he didn't feel the same way for most of their relationship.`);

INSERT INTO Personalities (personType, personTitle, personWords, personDescription, personImageURL, personStrengths, personWeaknesses, personOverview, mentalAgeTitle, mentalAgeDescription, animalTitle, animalDescription, officeTitle, officeDescription, pizzaTitle, pizzaDescription, coffeeTitle, coffeeDescription, travelTitle, travelDescription) 
VALUES 
(`ENFP`, `ENFP: The Champion`, `(Extroverted, Intuitive, Feeling, Perceiving)`, `ENFP is an acronym used to describe one of the sixteen personality types created by Katharine Briggs and Isabel Myers. It stands for Extraverted, iNtuitive, Feeling, Perceiving. ENFP indicates a person who is energized by time spent with others (Extraverted), who focuses on ideas and concepts rather than facts and details (iNtuitive), who makes decisions based on feelings and values (Feeling) and who prefers to be spontaneous and flexible rather than planned and organized (Perceiving). ENFPs are sometimes referred to as Champion personalities because of their enthusiasm for helping others realize their dreams.`, `ENFP.png`, `Excellent communicators
Imaginative
Natural leaders
Strong social conscience`, `Hypersensitivity
Lack of focus and follow through
Overthink things
Overemotional and approval-seeking`, `ENFPs are people-centered creators with a focus on possibilities and a contagious enthusiasm for new ideas, people and activities. Energetic, warm, and passionate, ENFPs love to help other people explore their creative potential.

ENFPs are typically agile and expressive communicators, using their wit, humor, and mastery of language to create engaging stories. Imaginative and original, ENFPs often have a strong artistic side. They are drawn to art because of its ability to express inventive ideas and create a deeper understanding of human experience.`, `ENFP – 21`, `No matter how old you become, you maintain the drive, enthusiasm and passion of someone who is just coming into his or her own. You are young at heart but old in spirit – you may best be described as 21 going on 90. You have the energy of someone much younger than yourself but the wisdom of someone much older.`, `ENFP – The Dolphin`, `Smart, friendly, and curious – dolphins capture many of the personality traits we love about ENFPs. These marine mammals are very creative and inventive, finding unique ways to capture fish and survive. For example, they sometimes wear sponges on their noses to protect themselves near rocks. They’re also capable of playing, tumbling, leaping, and socializing for enjoyment and fun. Like ENFPs, their creativity knows no bounds!`, `ENFP: Erin Hannon`, `People who have ENFP personalities tend to care a lot about others, and have outgoing personalities. However, they also tend to have their heads in the clouds, just like Erin usually does, so you have to understand that sometimes, they're going to throw away a disposable camera after taking a photo with it. But that's also part of Erin's charm, and just like many ENFPs, she's always fun, and she's always a ray of sunshine.`);

INSERT INTO Personalities (personType, personTitle, personWords, personDescription, personImageURL, personStrengths, personWeaknesses, personOverview, mentalAgeTitle, mentalAgeDescription, animalTitle, animalDescription, officeTitle, officeDescription, pizzaTitle, pizzaDescription, coffeeTitle, coffeeDescription, travelTitle, travelDescription) 
VALUES 
(`INTJ`, `INTJ: The Mastermind`, `(Introverted, Intuitive, Thinking, Judging)`, `INTJ is an acronym used to describe one of the sixteen personality types created by Katharine Briggs and Isabel Myers. It stands for Introverted, iNtuitive, Thinking, Judging. INTJ indicates a person who is energized by time alone (Introverted), who focuses on ideas and concepts rather than facts and details (iNtuitive), who makes decisions based on logic and reason (Thinking) and who prefers to be planned and organized rather than spontaneous and flexible (Judging). INTJs are sometimes referred to as Mastermind personalities because of their strategic, logical way of thinking.`, `INTJ.png`, `Strategy
Innovation
Determination
Willingness to learn`, `Superiority
Emotional distance
Perfectionism
Imbalance`, `INTJs are analytical problem-solvers, eager to improve systems and processes with their innovative ideas. They have a talent for seeing possibilities for improvement, whether at work, at home, or in themselves.

Often intellectual, INTJs enjoy logical reasoning and complex problem-solving. They approach life by analyzing the theory behind what they see, and are typically focused inward, on their own thoughtful study of the world around them. INTJs are drawn to logical systems and are much less comfortable with the unpredictable nature of other people and their emotions. They are typically independent and selective about their relationships, preferring to associate with people who they find intellectually stimulating.`, `INTJ – 80`, `INTJs seem to mentally age at twice the rate of most other types. Their lifelong quest for knowledge means they advance intellectually in leaps and bounds – they have little patience for the constraints of youth and tend to befriend adults from the time they are young. This type has the wisdom of an old soul and the unconquerable thirst for knowledge that keeps them growing and expanding well beyond their years.`, `INTJ – The Octopus`, ` Creative, clever, and strategic, the octopus captures the outside-the-box intelligence of the INTJ. These invertebrates are powerful hunters, strategically creating ways to outsmart predators. They can navigate their way through mazes, solve problems quickly, and even play – which is a clear sign of animal intelligence. They think quickly, using their pincers to grasp food and tear it apart or ejecting an inky cloud of darkness to evade predators.`, `INTJ: Darryl Philbin`, `Those who identify as INTJ are known as 'the architect,' and since the 16 Personalities site describes them as 'ambitious but private,' this description definitely fits Darryl perfectly. For seasons, he talked about his 'big plans' for Dunder Mifflin before leaving to join Athlead with Jim. He was never ready to settle and always wanted to keep moving in his career — and managed to work his way up from the warehouse. If you're anything like Darryl, chances are you are also hard working with a good imagination, and you're probably also good at more than one thing, just like he easily adapted from the warehouse to working upstairs in the office.`);

INSERT INTO Personalities (personType, personTitle, personWords, personDescription, personImageURL, personStrengths, personWeaknesses, personOverview, mentalAgeTitle, mentalAgeDescription, animalTitle, animalDescription, officeTitle, officeDescription, pizzaTitle, pizzaDescription, coffeeTitle, coffeeDescription, travelTitle, travelDescription) 
VALUES 
(`ENTJ`, `ENTJ: The Commander`, `(Extroverted, Intuitive, Thinking, Judging)`, `ENTJ is an acronym used to describe one of the sixteen personality types created by Katharine Briggs and Isabel Myers. It stands for Extraverted, iNtuitive, Thinking, Judging. ENTJ indicates a person who is energized by time spent with others (Extraverted), who focuses on ideas and concepts rather than facts and details (iNtuitive), who makes decisions based on logic and reason (Thinking) and who prefers to be planned and organized rather than spontaneous and flexible (Judging). ENTJs are sometimes referred to as Commander personalities because of their innate drive to lead others.`, `ENTJ.png`, `Strong willed
Efficient
Strategic thinking
Charismatic leader`, `Blunt and dominant
Intolerant
Arrogant
Poor handling of emotion`, `ENTJs are strategic leaders, motivated to organize change. They are quick to see inefficiency and conceptualize new solutions, and enjoy developing long-range plans to accomplish their vision. They excel at logical reasoning and are usually articulate and quick-witted.

ENTJs are analytical and objective, and like bringing order to the world around them. When there are flaws in a system, the ENTJ sees them, and enjoys the process of discovering and implementing a better way. ENTJs are assertive and enjoy taking charge; they see their role as that of leader and manager, organizing people and processes to achieve their goals.`, `ENTJ – 55`, `The age of the average Fortune 500 CEO is 55 so it seemed only natural that this age would suit you best. For the majority of your life you’ve possessed the confidence, diligence and decisiveness of someone much older than yourself – and by middle age your body will finally catch up with the maturity of your mind. 55 may just be your time to shine… but who are we kidding. Your whole life is your time to shine.`, `ENTJ – The Cheetah`, `Self-sufficient, determined, and insightful about their prey – cheetahs capture the restless, ambitious spirit of the ENTJ. Known to be hard-working and somewhat impatient, ENTJs would appreciate that cheetahs are the fastest land animals in the world – sometimes reaching 112km/h in just three seconds! Like ENTJs, cheetahs also value autonomy, freedom, and a prepared responsiveness to life.`, `ENTJ: Michael Scott`, `ENTJs are extroverted, natural leaders, and that definitely applies to Michael (even if his employees might not think that he truly belongs in a leadership role). He sets big goals — like finding a cure for rabies or outpacing China as the world's super power — and goes for them full throttle, even if he has no idea how to truly achieve them. ENTJs also aren't always the most in tune with other people's feelings, which would certainly explain a lot of Michael behavior in his love life before he married Holly.`);

INSERT INTO Personalities (personType, personTitle, personWords, personDescription, personImageURL, personStrengths, personWeaknesses, personOverview, mentalAgeTitle, mentalAgeDescription, animalTitle, animalDescription, officeTitle, officeDescription, pizzaTitle, pizzaDescription, coffeeTitle, coffeeDescription, travelTitle, travelDescription) 
VALUES 
(`ENTP`, `ENTP: The Visionary`, `(Extroverted, Intuitive, Thinking, Perceiving)`, `ENTP is an acronym used to describe one of the sixteen personality types created by Katharine Briggs and Isabel Myers. It stands for Extraverted, iNtuitive, Thinking, Perceiving. ENTP indicates a person who is energized by time spent with others (Extraverted), who focuses on ideas and concepts rather than facts and details (iNtuitive), who makes decisions based on logic and reason (Thinking) and who prefers to be spontaneous and flexible rather than planned and organized (Perceiving). ENTPs are sometimes referred to as Visionary personalities because of their passion for new, innovative ideas.`, `ENTP.png`, `Fearlessness
Innovation
Adaptability
Confidence`, `Flightiness
Impracticality
Breaking norms
Procrastination`, `ENTPs are inspired innovators, motivated to find new solutions to intellectually challenging problems. They are curious and clever, and seek to comprehend the people, systems, and principles that surround them. Open-minded and unconventional, Visionaries want to analyze, understand, and influence other people.

ENTPs enjoy playing with ideas and especially like to banter with others. They use their quick wit and command of language to keep the upper hand with other people, often cheerfully poking fun at their habits and eccentricities. While the ENTP enjoys challenging others, in the end they are usually happy to live and let live. They are rarely judgmental, but they may have little patience for people who can't keep up.`, `ENTP – 24`, `You have the innovative spirit of an idealistic child mixed with the professional savviness of an assertive adult – landing you squarely in the ‘young adult’ age bracket, mentally. No matter how old you get, you retain the adventurous, opportunistic nature of someone much younger than yourself, combined with the resourceful capability of someone much older.`, `ENTP – The Chimpanzee`, `Intelligent, innovative, and adventurous – chimpanzees embody many of the strengths of the ENTP personality type. They creatively build, invent games, enjoy playing, and have complex social relationships. Their innovative nature gives them the capacity to create their own spears to hunt for prey or even use long branches to dig for termites. This ability to adapt to their environment, be resourceful, and communicate with others in their troop reminds us of the sociability and imaginative intelligence of the ENTP.`, `ENTP: Jan Levinson`, `It goes without saying that Jan has one of the biggest personalities on the show, so she'd definitely be an ENTP. The fact that she doesn't hold back during arguments and likes to put everything out there is very typical of her personality type. She's ambitious and easily engages people, but on the downside, she also loves a good fight... and sometimes, someone's tiny plasma TV will get caught in the crossfire.`);

INSERT INTO Personalities (personType, personTitle, personWords, personDescription, personImageURL, personStrengths, personWeaknesses, personOverview, mentalAgeTitle, mentalAgeDescription, animalTitle, animalDescription, officeTitle, officeDescription, pizzaTitle, pizzaDescription, coffeeTitle, coffeeDescription, travelTitle, travelDescription) 
VALUES 
(`INTP`, `INTP: The Architect`, `(Introverted, Intuitive, Thinking, Perceiving)`, `INTP is an acronym used to describe one of the sixteen personality types created by Katharine Briggs and Isabel Myers. It stands for Introverted, iNtuitive, Thinking, Perceiving. INTP indicates a person who is energized by time alone (Introverted), who focuses on ideas and concepts rather than facts and details (iNtuitive), who makes decisions based on logic and reason (Thinking) and who prefers to be spontaneous and flexible rather than planned and organized (Perceiving). INTPs are sometimes referred to as Architect personalities because of their intuitive understanding of complex systems.`, `INTP.png`, `Analytically brilliance
Objective
Imaginative
Enthusiastic`, `Uncertainty
Absent-mindedness
Condescension
Insensitivity`, `INTPs are philosophical innovators, fascinated by logical analysis, systems, and design. They are preoccupied with theory, and search for the universal law behind everything they see. They want to understand the unifying themes of life, in all their complexity.

INTPs are detached, analytical observers who can seem oblivious to the world around them because they are so deeply absorbed in thought. They spend much of their time focused internally: exploring concepts, making connections, and seeking understanding. To the Architect, life is an ongoing inquiry into the mysteries of the universe.`, `INTP – 45`, `Of all the types, INTPs may be the most difficult to fit into a particular mental age. This type has the intellectual capacity and decisiveness of someone much older than themselves combined with the insatiable curiosity of a very young child. This type may best be described as “45 going on 3.” Their unique way of perceiving the world renders them ageless in many ways – they may be totally inept at ‘adulting’ but intellectually gifted from a young age.`, `INTP – The Green Anole Lizard`, `Clever, adaptable, and curious, these beautiful lizards capture some of the brain-power and critical thinking skills common of INTPs! They have shown an ability to count, problem-solve, and modify their learning depending on their environment. Some herpetologists believe that anoles are so intelligent and quick to learn because they’ve lived in complex environments where insects are difficult to capture.  Like INTPs, they adapt to their environment and find innovative, creative ways to stay at the top of their game.`, `INTP: Dwight Schrute`, `Although INTP personalities are creative, they're also obsessed with logic — something that sounds a lot like Dwight, who loves being right. As an INTP, it's no surprise that he's always trying to start new businesses to make money (Dwight Schrute's Gym For Muscles, anyone?). At work, Dwight is always striving to be the best salesman, and if it were up to him, there wouldn't be any of the office birthday parties that Michael loves so much, which is typical INTP behavior.`);

INSERT INTO Personalities (personType, personTitle, personWords, personDescription, personImageURL, personStrengths, personWeaknesses, personOverview, mentalAgeTitle, mentalAgeDescription, animalTitle, animalDescription, officeTitle, officeDescription, pizzaTitle, pizzaDescription, coffeeTitle, coffeeDescription, travelTitle, travelDescription) 
VALUES 
(`ESFJ`, `ESFJ: The Provider`, `(Extroverted, Sensing, Feeling, Judging)`, `ESFJ is an acronym used to describe one of the sixteen personality types created by Katharine Briggs and Isabel Myers. It stands for Extraverted, Sensing, Feeling, Judging. ESFJ indicates a person who is energized by time spent with others (Extraverted), who focuses on facts and details rather than ideas and concepts (Sensing), who makes decisions based on feelings and values (Feeling) and who prefers to be planned and organized rather than spontaneous and flexible (Judging). ESFJs are sometimes referred to as Provider personalities because of their interest in taking care of others in practical ways.`, `ESFJ.png`, `Strong practical skills
Warm and sensitive
Loyal and dutiful
Stand up and be counted`, `Rigid and judgmental
Reluctant to improvise
Neediness
Lack of creative thinking`, `ESFJs are conscientious helpers, sensitive to the needs of others and energetically dedicated to their responsibilities. They are highly attuned to their emotional environment and attentive to both the feelings of others and the perception others have of them. ESFJs like a sense of harmony and cooperation around them, and are eager to please and provide.

ESFJs value loyalty and tradition, and usually make their family and friends their top priority. They are generous with their time, effort, and emotions. They often take on the concerns of others as if they were their own, and will attempt to put their significant organizational talents to use to bring order to other people's lives.`, `ESFJ – 30`, `You’re bubbly, energetic and lively but also mature, responsible and organized – embodying all the qualities of someone who has grown confidently into young adulthood. They say our early thirties are our prime years – when we are old enough to have established ourselves, yet young enough to enjoy good health. And if you’re anything, it’s confident and established. You’ve always possessed the focus and maturity of a true adult, with the warmth and energy of someone much younger.`, `ESFJ – The Vampire Bat`, `Nurturing, practical, and surprisingly smart – the vampire bat might seem like an odd choice, but it actually makes sense. These often underestimated creatures have a giant neocortex which allows them to have complex social bonds. They maintain long-term relationships with other bands and will bond for years, taking care of each other’s young, grooming, and sharing food. Like ESFJs, vampire bats believe in taking care of each other and realize that safety and security is found when you have a solid support group.`, `ESFJ: Phyllis Vance`, `As an ESFJ, Phyllis is surprisingly social and warm (even though she does tend to get a bit sassy from time to time, when the situation calls for it — and even when it doesn't). She also enjoys organizing parties, which is a very ESFJ thing to do... and when Angela tries to take full control, it's also very ESFJ for her to call her out. Or, you know, tell the entire office that she's cheating on Andy.`);

INSERT INTO Personalities (personType, personTitle, personWords, personDescription, personImageURL, personStrengths, personWeaknesses, personOverview, mentalAgeTitle, mentalAgeDescription, animalTitle, animalDescription, officeTitle, officeDescription, pizzaTitle, pizzaDescription, coffeeTitle, coffeeDescription, travelTitle, travelDescription) 
VALUES 
(`ESFP`, `ESFP: The Performer`, `(Extroverted, Sensing, Feeling, Perceiving)`, `ESFP is an acronym used to describe one of the sixteen personality types created by Katharine Briggs and Isabel Myers. It stands for Extraverted, Sensing, Feeling, Perceiving. ESFP indicates a person who is energized by time spent with others (Extraverted), who focuses on facts and details rather than ideas and concepts (Sensing), who makes decisions based on feelings and values (Feeling) and who prefers to be spontaneous and flexible rather than planned and organized (Perceiving). ESFPs are sometimes referred to as Performer personalities because of their playful, energetic nature.`, `ESFP.png`, `Showmanship
Supportive
Positivity
Bold and practical`, `Avoid conflict
Sensitive
Easily bored
Poor long-term focus`, `ESFPs are vivacious entertainers who charm and engage those around them. They are spontaneous, energetic, and fun-loving, and take pleasure in the things around them: food, clothes, nature, animals, and especially people.

ESFPs are typically warm and talkative and have a contagious enthusiasm for life. They like to be in the middle of the action and the center of attention. They have a playful, open sense of humor, and like to draw out other people and help them have a good time.`, `ESFP – 16`, `It’s not that you lack the maturity or depth of your true biological age – it’s just that you embody the enthusiastic spirit of someone much younger than yourself. You are ceaselessly open to life in every facet. You work hard, play hard, love hard and live hard. Regardless of how old you become, you maintain the effervescent energy of someone much younger than yourself and it’s refreshing to everyone around you.`, `ESFP – The Blue and Gold Macaw`, `Loving, playful, and bright – the blue and gold macaw is known for its big personality and so are ESFPs! Like ESFPs, these particular macaws are adaptable, adventurous, and quick learners. They love to socialize and enjoy interacting with a variety of people. Highly observant, they enjoy being surrounded by people they love and new and interesting landscapes.`, `ESFP: Andy Bernard`, `ESFPs are known as entertainers, and has there ever been a better word to describe Andy Bernard? He's always trying to be the center of attention — especially when it comes to his musical skills — and as it turns out, that's just typical ESFP behavior. He likes to keep things fun and upbeat around the office, even if sometimes he loses his temper... or tries to drive his Prius under five miles an hour to win a duel with Dwight. ESFPs' feelings are easily hurt, and poor Andy definitely falls into that category at times.`);

INSERT INTO Personalities (personType, personTitle, personWords, personDescription, personImageURL, personStrengths, personWeaknesses, personOverview, mentalAgeTitle, mentalAgeDescription, animalTitle, animalDescription, officeTitle, officeDescription, pizzaTitle, pizzaDescription, coffeeTitle, coffeeDescription, travelTitle, travelDescription) 
VALUES 
(`ISFJ`, `ISFJ: The Protector`, `(Introverted, Sensing, Feeling, Judging)`, `ISFJ is an acronym used to describe one of the sixteen personality types created by Katharine Briggs and Isabel Myers. It stands for Introverted, Sensing, Feeling, Judging. ISFJ indicates a person who is energized by time spent alone (Introverted), who focuses on facts and details rather than ideas and concepts (Sensing), who makes decisions based on feelings and values (Feeling) and who prefers to be planned and organized rather than spontaneous and flexible (Judging). ISFJs are sometimes referred to as Protector personalities because of their interest in keeping people safe and well cared for.`, `ISFJ.png`, `Practical
Hardworking
Supportive
True to their word`, `Resistant to change
Too altruistic
Take things personally
Overload themselves`, `ISFJs are industrious caretakers, loyal to traditions and organizations. They are practical, compassionate, and caring, and are motivated to provide for others and protect them from the perils of life.

ISFJs are conventional and grounded, and enjoy contributing to established structures of society. They are steady and committed workers with a deep sense of responsibility to others. They focus on fulfilling their duties, particularly when they are taking care of the needs of other people. They want others to know that they are reliable and can be trusted to do what is expected of them. They are conscientious and methodical, and persist until the job is done.`, `ISFJ – 65`, `You’ve always felt a little out of sorts around people your own age – like some part of you would rather be at home, baking cookies with your cat, than out at a wild rager. You were born with the mentality of a calm, collected adult and it hasn’t wavered much over the years. You know old age will be your time to shine. You’ll be the best gran or grandpa on the block.`, `ISFJ – The Penguin`, `Loyal, protective, and intelligent, penguins have a lot of qualities in common with ISFJs! These arctic birds have complex social abilities and will go to great lengths to take care of each other. They also have a remarkable memory for detail – returning to the same spot year after year and being able to find it, even if the landscape has changed or it’s surrounded by other colonies. Like ISFJs, penguins are also fiercely loyal, staying monogamous and recognizing their partners’ song, even in noisy colonies where hundreds of penguins are searching for each other. This ability to hone in on one individual is a trait that penguins share with humans!`, `ISFJ: Jim Halpert`, `At work, ISFJs are loyal, low-drama, and dedicated — and minus his pranks on Dwight, that's definitely Jim, because if he wasn't loyal why else would he have stayed at Dunder Mifflin so long (you know, besides for the receptionist). They're also known as imaginative people, which also applies to Jim... going back to those pranks, of course.`);

INSERT INTO Personalities (personType, personTitle, personWords, personDescription, personImageURL, personStrengths, personWeaknesses, personOverview, mentalAgeTitle, mentalAgeDescription, animalTitle, animalDescription, officeTitle, officeDescription, pizzaTitle, pizzaDescription, coffeeTitle, coffeeDescription, travelTitle, travelDescription) 
VALUES 
(`ISFP`, `ISFP: The Composer`, `(Introverted, Sensing, Feeling, Perceiving)`, `ISFP is an acronym used to describe one of the sixteen personality types created by Katharine Briggs and Isabel Myers. It stands for Introverted, Sensing, Feeling, Perceiving. ISFP indicates a person who is energized by time spent alone (Introverted), who focuses on facts and details rather than ideas and concepts (Sensing), who makes decisions based on feelings and values (Feeling) and who prefers to be spontaneous and flexible rather than planned and organized (Perceiving). ISFPs are sometimes referred to as Composer personalities because of their innate sensibility for creating aesthetically pleasing experiences.`, `ISFP.png`, `Observant
Bold and spontaneous 
Principled
Individual`, `Too sensitive
Indecisive and unpredictable
Easily bored
Lack of future planning`, `ISFPs are gentle caretakers who live in the present moment and enjoy their surroundings with cheerful, low-key enthusiasm. They are flexible and spontaneous, and like to go with the flow to enjoy what life has to offer. ISFPs are quiet and unassuming, and may be hard to get to know. However, to those who know them well, the ISFP is warm and friendly, eager to share in life's many experiences.

ISFPs have a strong aesthetic sense and seek out beauty in their surroundings. They are attuned to sensory experience, and often have a natural talent for the arts. ISFPs especially excel at manipulating objects, and may wield creative tools like paintbrushes and sculptor's knives with great mastery.`, `ISFP – 23`, `They say your early to mid twenties are your peak creative years – but for you, your entire life is your peak creative years. Possessing the insight of someone much older than yourself but the youthful creative energy of someone much younger, your age might best be described as '23 going on 60.'`, `ISFP – The Leopard`, `Elusive, empathetic, and striking – the leopard captures the enigmatic nature of the ISFP. Like ISFPs, these big cats enjoy their solitude but have an unusual empathy for other creatures at times. During a National Geographic program called ‘Eye of the Leopard’, a wild leopard killed a baboon in order to feed herself. However, once she noticed the infant baboon clinging to its mother, she groomed and cuddled the baby throughout the night as if it were her own cub.  Like the ISFP, the leopard is cunning, resourceful, and likes its space and alone time.`, `ISFP: Meredith Palmer`, `ISFPs like Meredith are spontaneous people who love taking risks and don't take criticism well when they don't agree with it — which is basically Meredith anytime someone reminds her she needs to wear underwear in the office. ISFP personalities are also known to be a bit too independent, and in the workplace, they don't always follow the rules... kind of like that time Meredith admitted she sleeps with someone at a paper supplier for lower overhead costs and Outback gift cards. But at least she gets the job done?`);

INSERT INTO Personalities (personType, personTitle, personWords, personDescription, personImageURL, personStrengths, personWeaknesses, personOverview, mentalAgeTitle, mentalAgeDescription, animalTitle, animalDescription, officeTitle, officeDescription, pizzaTitle, pizzaDescription, coffeeTitle, coffeeDescription, travelTitle, travelDescription) 
VALUES 
(`ESTJ`, `ESTJ: The Supervisor`, `(Extroverted, Sensing, Thinking, Judging)`, `ESTJ is an acronym used to describe one of the sixteen personality types created by Katharine Briggs and Isabel Myers. It stands for Extraverted, Sensing, Thinking, Judging. ESTJ indicates a person who is energized by time spent with others (Extraverted), who focuses on facts and details rather than ideas and concepts (Sensing), who makes decisions based on logic and reason (Thinking) and who prefers to be planned and organized rather than spontaneous and flexible (Judging). ESTJs are sometimes referred to as Supervisor personalities because they tend to take charge and make sure things are done correctly.`, `ESTJ.png`, `Organization and efficiency
Dedication and commitment
Integrity
Stewardship`, `Judgemental
Uncomfortable with emotions
Workaholism
Stubborn and inflexible`, `ESTJs are hardworking traditionalists, eager to take charge in organizing projects and people. Orderly, rule-abiding, and conscientious, ESTJs like to get things done, and tend to go about projects in a systematic, methodical way.

ESTJs are the consummate organizers, and want to bring structure to their surroundings. They value predictability and prefer things to proceed in a logical order. When they see a lack of organization, the ESTJ often takes the initiative to establish processes and guidelines, so that everyone knows what's expected.`, `ESTJ – 45`, `ESTJs combine the playful, gregarious spirit of a young college bro with the responsibility and diligence of a fully-formed adult. This type is obsessively professional and capable – they enjoy middle age as a time where they have earned the respect of their peers yet are still in good enough health to be able to push their own limits.`, `ESTJ – The Wolf`, `Dedicated, focused, and intelligent – wolves work in groups to take care of their pack. The ESTJ would probably be the alpha wolf, leading the pack and organizing the best hunting methods. Deeply loyal, wolves will actually develop very close relationships and bonds with each other. When they mate they mate for life, and may even sacrifice themselves for their family unit! This steadfast loyalty and determination is something we love about most ESTJs.`, `ESTJ: Holly Flax`, `It's no surprise that if you're an ESTJ, you're a lot like Holly, because she's totally typical of this personality type. She fights for what's right, even if that just extends to the HR department, and loves rules and order, which is why she was so upset when the company let that incident with Meredith and the Outback cards slide. ESTJs also don't like to waste time with relationships that aren't going anywhere, so it makes sense that she was quick to dump AJ when he wouldn't propose to her. And now, she gets to live happily ever after with Michael, which is all any of us really wanted.`);

INSERT INTO Personalities (personType, personTitle, personWords, personDescription, personImageURL, personStrengths, personWeaknesses, personOverview, mentalAgeTitle, mentalAgeDescription, animalTitle, animalDescription, officeTitle, officeDescription, pizzaTitle, pizzaDescription, coffeeTitle, coffeeDescription, travelTitle, travelDescription) 
VALUES 
(`ESTP`, `ESTP: The Persuader`, `(Extroverted, Sensing, Thinking, Perceiving)`, `ESTP is an acronym used to describe one of the sixteen personality types created by Katharine Briggs and Isabel Myers. It stands for Extraverted, Sensing, Thinking, Perceiving. ESTP indicates a person who is energized by time spent with others (Extraverted), who focuses on facts and details rather than ideas and concepts (Sensing), who makes decisions based on logic and reason (Thinking) and who prefers to be spontaneous and flexible rather than planned and organized (Perceiving). ESTPs are sometimes referred to as Dynamo personalities because of their high-energy, active approach to life.`, `ESTP.png`, `Can-do attitude
Bold
Personable and sociable
Direct`, `Judgemental
Impatient
Unstructured
Commitment phobic`, `ESTPs are energetic thrillseekers who are at their best when putting out fires, whether literal or metaphorical. They bring a sense of dynamic energy to their interactions with others and the world around them. They assess situations quickly and move adeptly to respond to immediate problems with practical solutions.

Active and playful, ESTPs are often the life of the party and have a good sense of humor. They use their keen powers of observation to assess their audience and adapt quickly to keep interactions exciting. Although they typically appear very social, they are rarely sensitive; the ESTP prefers to keep things fast-paced and silly rather than emotional or serious.`, `ESTP – 18`, `ESTPs are the straight-shooting rule-breakers of the world, who never fully lose their rebellious teenage spirit. This type retains the energy and enthusiasm of a young adult no matter how old they get. They won’t be held back by the world around them – they get what they want when they want it and just try telling them otherwise.`, `ESTP – The Fox`, `Adaptable, smart, powerful – the fox embodies many of the natural strengths of the ESTP. Like the ESTP, foxes trust their instincts and use their quick-thinking skills to survive and succeed in life. They are ceaselessly curious, playful, and often friendly – especially if they’ve been raised among humans. Just don’t get near these playful creatures – sometimes they (foxes, not ESTPs) can carry rabies!`, `ESTP: Ryan Howard`, `ESTPs are known as entrepreneurs, always fighting for career advancement — and that's Ryan, until he lost it all and started working at that bowling alley, anyway. However, they can also be known to be insensitive, which we've definitely witnessed in Ryan's interactions toward other people (especially Kelly). On the bright side, ESTPs like Ryan are also very bold and direct, which comes in handy in all kinds of situations.`);

INSERT INTO Personalities (personType, personTitle, personWords, personDescription, personImageURL, personStrengths, personWeaknesses, personOverview, mentalAgeTitle, mentalAgeDescription, animalTitle, animalDescription, officeTitle, officeDescription, pizzaTitle, pizzaDescription, coffeeTitle, coffeeDescription, travelTitle, travelDescription) 
VALUES 
(`ISTJ`, `ISTJ: The Inspector`, `(Introverted, Sensing, Thinking, Judging)`, `ISTJ is an acronym used to describe one of the sixteen personality types created by Katharine Briggs and Isabel Myers. It stands for Introverted, Sensing, Thinking, Judging. ISTJ indicates a person who is energized by time spent alone (Introverted), who focuses on facts and details rather than ideas and concepts (Sensing), who makes decisions based on logic and reason (Thinking) and who prefers to be planned and organized rather than spontaneous and flexible (Judging). ISTJs are sometimes referred to as Inspector personalities because of their focus on details and interest in doing things correctly.`, `ISTJ.png`, `Perseverance
Planning
Detail orientation
Loyalty`, `Stubbornness
Tactlessness
Guilt
Resistance to change`, `ISTJs are responsible organizers, driven to create and enforce order within systems and institutions. They are neat and orderly, inside and out, and tend to have a procedure for everything they do. Reliable and dutiful, ISTJs want to uphold tradition and follow regulations.

ISTJs are steady, productive contributors. Although they are Introverted, ISTJs are rarely isolated; typical ISTJs know just where they belong in life, and want to understand how they can participate in established organizations and systems. They concern themselves with maintaining the social order and making sure that standards are met.`, `ISTJ – 50`, `ISTJs are born responsible. This type takes their commitments direly seriously and possesses almost no trace of youthful mischievousness. They often feel older than their peers, even as children, and long to reach an age at which they will finally be taken seriously by their peers. Middle age suits the ISTJ well – they are still physically capable of getting things done, while finally being old enough to receive the respect they deserve.`, `ISTJ – The Great Horned Owl`, `Observant, protective, and revered as wise, the great horned owl captures many of the things we love about ISTJs. These mysterious-looking birds are solitary in nature, preferring to stay with their mates or families. They also are extremely focused and attentive – gliding slowly above the ground to catch unsuspecting prey. Like ISTJs these birds like to keep to themselves, but they are also very dedicated to their loved ones and very hard-working in providing for them.`, `ISTJ: Oscar Martinez`, `ISTJs take their jobs seriously and like to do well at work — just like Oscar in the accounting department. Logic and reason are important to people with this personality type, just like they are with Oscar... who's known around the office for correcting people with an 'actually' statement that no one ever asked for. Oscar loves to be right, and if you're an ISTJ, that probably applies to you too.`);

INSERT INTO Personalities (personType, personTitle, personWords, personDescription, personImageURL, personStrengths, personWeaknesses, personOverview, mentalAgeTitle, mentalAgeDescription, animalTitle, animalDescription, officeTitle, officeDescription, pizzaTitle, pizzaDescription, coffeeTitle, coffeeDescription, travelTitle, travelDescription) 
VALUES 
(`ISTP`, `ISTP: The Craftman`, `(Introverted, Sensing, Thinking, Perceiving)`, `ISTP is an acronym used to describe one of the sixteen personality types created by Katharine Briggs and Isabel Myers. It stands for Introverted, Sensing, Thinking, Perceiving. ISTP indicates a person who is energized by time spent alone (Introverted), who focuses on facts and details rather than ideas and concepts (Sensing), who makes decisions based on logic and reason (Thinking) and who prefers to be spontaneous and flexible rather than planned and organized (Perceiving). ISTPs are sometimes referred to as Craftsperson personalities because they typically have an innate mechanical ability and facility with tools.`, `ISTP.png`, `Practical and creative
Problem solving
Common sense and world savvy
Flexible`, `Insensitive
Risk-seeking behavior
Impatient
Private and reserved`, `ISTJ is an acronym used to describe one of the sixteen personality types created by Katharine Briggs and Isabel Myers. It stands for Introverted, Sensing, Thinking, Judging. ISTJ indicates a person who is energized by time spent alone (Introverted), who focuses on facts and details rather than ideas and concepts (Sensing), who makes decisions based on logic and reason (Thinking) and who prefers to be planned and organized rather than spontaneous and flexible (Judging). ISTJs are sometimes referred to as Inspector personalities because of their focus on details and interest in doing things correctly.`, `ISTP – 22`, `ISTPs are in their prime when they are at their physical peak – usually in their early twenties. This type has a devilishly rebellious spirit that relishes in sensory delights. And yet they do possess the capability and responsibility of a quasi-adult at any age. 22 truly does seem to suit this type, as an age at which they are able to live life on their own terms but are not yet bothered by the societal expectations of adulthood.`, `ISTP – The Crow`, `Resourceful, independent, intelligent – the crow exemplifies many of the strengths of the ISTP. Like ISTPs, crows are excellent problem-solvers and masters with tools. Some crows can form probes and hooks from sticks and leaf stems to poke into the crowns of palm trees. Others gather nuts from trees and place them on the street for cars to crack open. When a crow dies, the other crows will gather around the crow to find out what killed the member. Then, they will band together and chase predators down in a behavior called “mobbing.” Their cleverness, curiosity, and craftsmanship abilities remind us of the ISTP intellect.`, `ISTP: Toby Flenderson`, `Above all else, ISTPs want to solve problems in a hands-on way, which is perfect for someone who works in HR. Like a typical ISTP personality, Toby likes to create fairness in the workplace (even if Michael often disagrees with what he's doing). He's not chatty, and he's not going to push things farther than they need to go — but unfortunately, nobody he works with really truly appreciates his management style.`);